name: Trigger-All-Workflows  # 主要工作流的名称

on:
  workflow_dispatch:  # 手动触发：通过 GitHub UI 来触发
  schedule:
    - cron: 25 20 * * *  # 北京时间星期六凌晨4点，定时触发

jobs:
    Arthur-Athena-Stable-V-NOWIFI:
     uses: ./.github/workflows/Arthur&Athena-Stable(V)-NOWIFI.yml

    # Arthur-Athena-Master-V:
    #  uses: ./.github/workflows/Arthur&Athena-Master(V).yml

    # Arthur-Athena-Stable-B:
    #  uses: ./.github/workflows/Arthur&Athena-Stable(B).yml

    # Arthur-Athena-Stable-V:
    #  uses: ./.github/workflows/Arthur&Athena-Stable(V).yml
 
    Taiyi-6-12:
      uses: ./.github/workflows/Taiyi-6.12.yml
 
    Taiyi-Master:
    uses: ./.github/workflows/Taiyi-Master.yml
 
    Taiyi-Stable:
    uses: ./.github/workflows/Taiyi-Stable.yml

    # All-Base:
    #  uses: ./.github/workflows/All-Base.yml

    # All-Clean:
    #  uses: ./.github/workflows/All-Clean.yml
